# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45f4bb2c6c6bdaf63e1c90707887fa57f595d4312d0370ea15b05b1e9bc91bff9a2eb31a14cb7d45bc7ace7b7ceca0332c72c0262cb3fa142e3da24acf5ed669

test:
  secret_key_base: 9416f48bd593c9eb852674ac1479b9793e50f769d1da7e00958863aa75e7a0d766cbf31849ac768a79e9eed69b9105cc5c15ca61053bd32a5a590f56301f3b50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
